#!/bin/bash
target="$PWD/assets"


while IFS="" read -r line || [ -n "$line" ]
do
  url=$(echo "$line" | cut -d ' ' -f1)
  name=$(echo "$line" | cut -d ' ' -f2)

  curl -L "$url" -o "$target"/"$name"

done < "$target"/deps.txt
